google-auth
prototype2010/classes-marketplace pull request #6
Opened 2020-11-02 12:17 UTC by prototype2010

2020-11-02 13:20 UTC, VinokurYurii requested changes

2020-11-02 13:20 UTC, VinokurYurii commented on src/auth/auth.controller.spec.ts
> +        await request(app.getHttpServer())
создание тестового юзера методами тестируемого контроллера - как-то не айс. Обычно для этого используют более прямые и надежные методы. Суть в том, что "бефорЕач" должен отрабатывать всегда, т.к. не он является предметом тестирования
+ в дальнейшем нам надо будет делать оправку емейла, и это будет происходить под капотом контроллера или сервиса, и получается у тебя каждое создание тестового юзера будет вызывать интересные сайд эфекты

2020-11-02 13:20 UTC, VinokurYurii commented on src/auth/auth.controller.ts
> +import { tsTsxJsJsxRegex } from 'ts-loader/dist/constants';
это не ошибка, но нест имеет много импортов, было бы неплохо придумать какой-то план по их очередности и следовать ему - иначе впечатление бардака

2020-11-02 13:20 UTC, VinokurYurii commented on src/auth/auth.controller.ts
> +    return this.authService.login(req.user);
тут вообще странно, надо обсудить

2020-11-02 13:20 UTC, VinokurYurii commented on src/auth/auth.controller.ts
> +import { SignInDTO, SignInSchema } from './dto/signin.dto';
тыж не используешь его тут

2020-11-02 13:20 UTC, VinokurYurii commented on src/entity/user.entity.ts
> +  @Column({ nullable: true, default: null })
какая смысловая нагрузка этого "default: null"?

2020-11-02 13:20 UTC, VinokurYurii commented on src/entity/user.entity.ts
> +  @Column({ nullable: true, default: null })
какая смысловая нагрузка этого "default: null"?

2020-11-02 13:20 UTC, VinokurYurii commented on src/entity/user.entity.ts
>    @Column({ nullable: false, default: false })
"nullable: false" - дефолтное значение для тайпОрм, смысла указывать нет

2020-11-02 13:20 UTC, VinokurYurii commented on src/users/user.repository.ts
> +  private async findUser(...params: Array<{ [key: string]: any }>) {
Array<{ [key: string]: any }> - по факту счтитай ты ничего этим не сказал, предлагаю обсудить, думаю тебе тут больше подойдет Partial<User>

2020-11-02 13:20 UTC, VinokurYurii commented on src/users/user.repository.ts
> +  private async createGoogleUserUser({
createGoogleUserUser

2020-11-02 13:20 UTC, VinokurYurii commented on src/users/user.repository.ts
> +    user.emailConfirmationHash = await this.hash(email);
А оно тебе надо учитывая  user.isEmailConfirmed = true; ?

2020-11-02 13:20 UTC, VinokurYurii commented on src/users/user.repository.ts
> +    user.firstName = firstName;
ты не пробовал тут Object.assign() ?

2020-11-02 15:18 UTC, prototype2010 commented on src/auth/auth.controller.ts
> +import { tsTsxJsJsxRegex } from 'ts-loader/dist/constants';
+

2020-11-02 16:08 UTC, prototype2010 commented on src/auth/auth.controller.ts
> +import { SignInDTO, SignInSchema } from './dto/signin.dto';
+

2020-11-02 16:09 UTC, prototype2010 commented on src/entity/user.entity.ts
> +  @Column({ nullable: true, default: null })
+

2020-11-02 16:10 UTC, prototype2010 commented on src/entity/user.entity.ts
>    @Column({ nullable: false, default: false })
+

2020-11-02 16:10 UTC, prototype2010 commented on src/entity/user.entity.ts
> +  @Column({ nullable: true, default: null })
+

2020-11-02 16:11 UTC, prototype2010 commented on src/users/user.repository.ts
> +  private async findUser(...params: Array<{ [key: string]: any }>) {
+

2020-11-02 16:11 UTC, prototype2010 commented on src/users/user.repository.ts
> +  private async createGoogleUserUser({
+

2020-11-03 08:33 UTC, prototype2010 commented on src/users/user.repository.ts
> +    user.emailConfirmationHash = await this.hash(email);
+

2020-11-03 08:34 UTC, prototype2010 commented on src/users/user.repository.ts
> +    user.firstName = firstName;
+

2020-11-03 10:21 UTC, prototype2010 commented on src/auth/auth.controller.spec.ts
> +        await request(app.getHttpServer())
+

2020-11-03 11:07 UTC, prototype2010 commented on src/auth/auth.controller.ts
> +    return this.authService.login(req.user);
+

2020-11-03 11:12 UTC, merged